int _putchar(char c);
void reset_to_98(int *n);
void swap_int(int *a, int *b);
int _strlen(char *s);
void _puts(char *str);
void print_rev(char *s);
void rev_string(char *s);
void print_most_numbers(void);
int print_sign(int n);
void print_line(int n);
void print_diagonal(int n);
void more_numbers(void);
void times_table(void);
int add(int, int);
void print_to_98(int n);
void print_times_table(int n);
